# Criando uma tabela com IDs, IDs completos, fenótipos, número de reads e etc

In [1]:
import pandas as pd
import re
import glob
import os

In [2]:
with open('/home/boralli/workdir/samples_30kkreads.csv') as f:
    fileSamples = pd.read_csv(f, sep=',')
fileSamples

       IDs  TotalReads Passed? Phenotype
0    R2809    34476986     Yes    Schizo
1    R2826    60779562     Yes   Control
2    R2828    82079232     Yes    Schizo
3    R2834    68803962     Yes    Schizo
4    R2836    12391034      No   Control
..     ...         ...     ...       ...
164  R5863    10460292      No   Control
165  R5868    31767848     Yes   Control
166  R5885    62490302     Yes   Control
167  R6533    40170560     Yes    Schizo
168  R6535    44172850     Yes    Schizo

[169 rows x 4 columns]

In [9]:
path = '/home/boralli/workdir/pipeline_v4/LOGS/FASTP_LOG/'
lista_nomes = []
pattern = r"R\d{4}_\w{9}_\w{6,8}_\w{4}_"
for filename in glob.glob(os.path.join(path, '*.html')):
#     lista_nomes.append(filename)
    regexList = re.findall(pattern, filename)
#     print (regexList)
    lista_nomes.extend(regexList)
        
lista_nomes = sorted(lista_nomes)

#adicionando a string _quant
string = '_quant'
lista_nomes_quant = [x + string for x in lista_nomes]

In [10]:
path_salmon = '/home/boralli/workdir/pipeline_v4/SALMON/output/'
lista_salmon = []
pattern = r"R\d{4}_\w{9}_\w{6,8}_\w{4}__quant"
for filename in glob.glob(os.path.join(path_salmon)):
#     lista_nomes.append(filename)
    regexList = re.findall(pattern, filename)
#     print (regexList)
    lista_salmon.extend(regexList)
        
lista_salmon = sorted(lista_nomes)

In [11]:
fileSamples['completeID'] = lista_nomes_quant

fileSamples

       IDs  TotalReads Passed? Phenotype                            completeID
0    R2809    34476986     Yes    Schizo  R2809_D2A01ACXX_TAATGCGC_L005__quant
1    R2826    60779562     Yes   Control    R2826_C00JVACXX_TGACCA_L001__quant
2    R2828    82079232     Yes    Schizo  R2828_C0UH3ACXX_TAATGCGC_L005__quant
3    R2834    68803962     Yes    Schizo    R2834_C0CEWACXX_ATCACG_L005__quant
4    R2836    12391034      No   Control  R2836_C3V3YACXX_CGGCTATG_L001__quant
..     ...         ...     ...       ...                                   ...
164  R5863    10460292      No   Control  R5863_C28MYACXX_CTGAAGCT_L001__quant
165  R5868    31767848     Yes   Control  R5868_C28MMACXX_GAATTCGT_L005__quant
166  R5885    62490302     Yes   Control    R5885_C0CEWACXX_TTAGGC_L003__quant
167  R6533    40170560     Yes    Schizo  R6533_C284PACXX_TCTCGCGC_L004__quant
168  R6535    44172850     Yes    Schizo  R6535_C284PACXX_TCCGGAGA_L005__quant

[169 rows x 5 columns]

In [12]:
#SALVANDO EM FORMATO CSV
fileSamples.to_csv(r'/home/boralli/workdir/pipeline_v4/DE/complete_samplesINFO.csv', index=True)

In [14]:
#FILTRANDO PASSED = NO
fileSamples_passed = fileSamples[fileSamples['Passed?']=='Yes']
fileSamples_passed

       IDs  TotalReads Passed? Phenotype                            completeID
0    R2809    34476986     Yes    Schizo  R2809_D2A01ACXX_TAATGCGC_L005__quant
1    R2826    60779562     Yes   Control    R2826_C00JVACXX_TGACCA_L001__quant
2    R2828    82079232     Yes    Schizo  R2828_C0UH3ACXX_TAATGCGC_L005__quant
3    R2834    68803962     Yes    Schizo    R2834_C0CEWACXX_ATCACG_L005__quant
5    R2839    37274500     Yes   Control  R2839_C0UH3ACXX_ATTACTCG_L001__quant
..     ...         ...     ...       ...                                   ...
163  R5861   113880898     Yes   Control    R5861_C0JKHACXX_GCCAAT_L001__quant
165  R5868    31767848     Yes   Control  R5868_C28MMACXX_GAATTCGT_L005__quant
166  R5885    62490302     Yes   Control    R5885_C0CEWACXX_TTAGGC_L003__quant
167  R6533    40170560     Yes    Schizo  R6533_C284PACXX_TCTCGCGC_L004__quant
168  R6535    44172850     Yes    Schizo  R6535_C284PACXX_TCCGGAGA_L005__quant

[128 rows x 5 columns]

In [15]:
#SALVANDO EM FORMATO CSV
fileSamples_passed.to_csv(r'/home/boralli/workdir/pipeline_v4/DE/complete_samplesINFO_passed.csv', index=True)